create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,username text unique not null,full_name text not null,role text not null default 'technician' check(role in('admin','supervisor','technician')),created_at timestamptz default now());
create table if not exists public.hmc_shift_entries(id bigint generated by default as identity primary key,report_date date not null,report_month text not null,shift1_status text not null default 'Standby',shift1_start time,shift1_end time,shift1_duration integer default 0,shift1_note text,shift2_status text not null default 'Standby',shift2_start time,shift2_end time,shift2_duration integer default 0,shift2_note text,detail text,created_by uuid references auth.users(id),updated_by uuid references auth.users(id),created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.breakdown_reports(id bigint generated by default as identity primary key,report_no integer not null,machine text not null default 'HMC',breakdown_date date not null,time_from time,time_to time,down_time_minutes integer default 0,problem_description text,checking_steps text,root_cause text,corrective_actions text,spare_parts text,pic text,stratification text,photo_url text,remarks text,created_by uuid references auth.users(id),updated_by uuid references auth.users(id),created_at timestamptz default now(),updated_at timestamptz default now());
alter table public.hmc_reports add column if not exists updated_by uuid references auth.users(id);
alter table public.hmc_shift_entries add column if not exists created_by uuid references auth.users(id); alter table public.hmc_shift_entries add column if not exists updated_by uuid references auth.users(id);
alter table public.breakdown_reports add column if not exists created_by uuid references auth.users(id); alter table public.breakdown_reports add column if not exists updated_by uuid references auth.users(id);
alter table public.hmc_shift_entries enable row level security; alter table public.breakdown_reports enable row level security; alter table public.profiles enable row level security;
create or replace function public.my_role() returns text language sql stable security definer set search_path=public as $$select role from public.profiles where id=auth.uid() limit 1$$;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.profiles(id,username,full_name,role) values(new.id,coalesce(split_part(new.email,'@',1),'user')||'_'||left(new.id::text,6),coalesce(new.raw_user_meta_data->>'full_name',split_part(coalesce(new.email,'user'),'@',1),'User'),'technician') on conflict(id) do nothing; return new; end;$$;
drop trigger if exists on_auth_user_created on auth.users; create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
insert into public.profiles(id,username,full_name,role) select u.id,coalesce(split_part(u.email,'@',1),'user')||'_'||left(u.id::text,6),coalesce(split_part(coalesce(u.email,'User'),'@',1),'User'),'technician' from auth.users u left join public.profiles p on p.id=u.id where p.id is null;
drop policy if exists profiles_read on public.profiles; create policy profiles_read on public.profiles for select to authenticated using(id=auth.uid() or public.my_role() in('admin','supervisor'));
drop policy if exists shift_read on public.hmc_shift_entries; drop policy if exists shift_insert on public.hmc_shift_entries; drop policy if exists shift_update on public.hmc_shift_entries; drop policy if exists shift_delete on public.hmc_shift_entries; create policy shift_read on public.hmc_shift_entries for select to authenticated using(true); create policy shift_insert on public.hmc_shift_entries for insert to authenticated with check(public.my_role() in('admin','supervisor','technician')); create policy shift_update on public.hmc_shift_entries for update to authenticated using(public.my_role() in('admin','supervisor','technician')) with check(public.my_role() in('admin','supervisor','technician')); create policy shift_delete on public.hmc_shift_entries for delete to authenticated using(true);
drop policy if exists breakdown_read on public.breakdown_reports; drop policy if exists breakdown_insert on public.breakdown_reports; drop policy if exists breakdown_update on public.breakdown_reports; drop policy if exists breakdown_delete on public.breakdown_reports; create policy breakdown_read on public.breakdown_reports for select to authenticated using(true); create policy breakdown_insert on public.breakdown_reports for insert to authenticated with check(public.my_role() in('admin','supervisor','technician')); create policy breakdown_update on public.breakdown_reports for update to authenticated using(public.my_role() in('admin','supervisor','technician')) with check(public.my_role() in('admin','supervisor','technician')); create policy breakdown_delete on public.breakdown_reports for delete to authenticated using(true);
insert into storage.buckets(id,name,public) values('hmc-breakdown-photos','hmc-breakdown-photos',true) on conflict(id) do update set public=true;
drop policy if exists hmc_photo_upload on storage.objects; drop policy if exists hmc_photo_read on storage.objects; create policy hmc_photo_upload on storage.objects for insert to authenticated with check(bucket_id='hmc-breakdown-photos'); create policy hmc_photo_read on storage.objects for select to public using(bucket_id='hmc-breakdown-photos');
notify pgrst,'reload schema';

-- FINAL V2: one date may contain multiple shift/event entries.
DO $$
DECLARE c_name text;
BEGIN
  SELECT conname INTO c_name FROM pg_constraint
  WHERE conrelid='public.hmc_shift_entries'::regclass
    AND contype='u'
    AND pg_get_constraintdef(oid) ILIKE '%(report_date)%' LIMIT 1;
  IF c_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE public.hmc_shift_entries DROP CONSTRAINT %I', c_name);
  END IF;
END $$;
NOTIFY pgrst, 'reload schema';
